"""
Agent 5 — Deck Content Writer Agent

All slide content is generated by the LLM using the actual extracted requirements
and architecture as context. Nothing is hardcoded.
"""
from __future__ import annotations
from datetime import date
from typing import List, Tuple

from models.schemas import (
    ArchitectureDescription, RequirementsAnalysis, DeckContent,
    RoleResponsibility, Assumption, Credential, PlanPhase,
)
from utils.llm import llm_json, llm_call
import config

_PLAIN = "Write plain text only — no markdown, no bullet points, no headers, no bold or italic markers."


# ── Shared context builder ────────────────────────────────────────────────────

def _ctx(arch: ArchitectureDescription, analysis: RequirementsAnalysis) -> str:
    """Compact project summary injected into every prompt."""
    feature_groups = sorted({r.feature_group for r in analysis.requirements if r.feature_group})
    cx = [r.complexity or "" for r in analysis.requirements]
    hi, md, lo = cx.count("High"), cx.count("Medium"), cx.count("Low")
    services = [s.name for s in arch.services]
    return (
        f"Platform: {arch.platform_name}\n"
        f"Requirements: {len(analysis.requirements)} total  ({hi} High / {md} Medium / {lo} Low complexity)\n"
        f"Feature groups: {', '.join(feature_groups[:10])}\n"
        f"Services: {', '.join(services[:8])}"
    )


# ── Content generators ────────────────────────────────────────────────────────

def _generate_governance(arch: ArchitectureDescription, analysis: RequirementsAnalysis) -> str:
    try:
        return llm_call(
            system=f"You are a senior project manager writing a proposal governance section. {_PLAIN}",
            user=(
                f"Write the governance and communication model (4-6 sentences) for this project:\n{_ctx(arch, analysis)}\n\n"
                "Cover: CET business hours, weekly status calls, sprint reviews, "
                "escalation path (PM → Steering Committee), and how client/vendor teams interact daily."
            ),
            max_tokens=400,
        )
    except Exception:
        return (
            "Weekly status calls are held every Monday at 10:00 CET with the core project team and client stakeholders. "
            "Sprint reviews occur bi-weekly with the product owner. "
            "Issues are escalated to the Project Manager first, then to the Steering Committee if unresolved within 48 hours."
        )


def _generate_delivery(
    arch: ArchitectureDescription, analysis: RequirementsAnalysis
) -> Tuple[str, str, str]:
    """Returns (delivery_method, team_structure, locations)."""
    try:
        raw = llm_call(
            system=f"You are writing a project proposal. {_PLAIN} Reply with exactly 3 parts separated by '|||'.",
            user=(
                f"For this project:\n{_ctx(arch, analysis)}\n\n"
                "Part 1: delivery method (one concise sentence — Agile cadence and sprint length).\n"
                "Part 2: team structure (2-3 sentences — roles, size, onsite/nearshore split).\n"
                "Part 3: location model (one sentence).\n\n"
                "Format: part1 ||| part2 ||| part3"
            ),
            max_tokens=400,
        )
        parts = [p.strip() for p in raw.split("|||")]
        if len(parts) == 3 and all(parts):
            return parts[0], parts[1], parts[2]
    except Exception:
        pass
    return (
        "Agile / Scrum — 2-week sprints",
        "The team comprises a Project Manager, Solution Architect, Business Analyst, Scrum Master, and a development squad of 3-5 engineers. Nearshore delivery with onsite presence for key workshops and go-live.",
        "Onsite (client workshops & go-live) + Nearshore (daily delivery)",
    )


def _generate_roles(arch: ArchitectureDescription, analysis: RequirementsAnalysis) -> List[RoleResponsibility]:
    try:
        data = llm_json(
            system="You are writing the Roles & Responsibilities matrix for a project proposal. Return a JSON array only — no prose.",
            user=(
                f"Generate 6-7 project roles for this project:\n{_ctx(arch, analysis)}\n\n"
                "Return a JSON array where each item has exactly these keys:\n"
                '  "role": string\n'
                '  "responsibilities": array of exactly 3 short strings\n'
                '  "outcomes": array of exactly 3 short measurable deliverable strings\n'
                '  "responsible_party": one of "Vendor", "Client", or "Joint"\n\n'
                "Always include: Project Owner (Client), Project Manager (Vendor), "
                "Business Analyst (Vendor), Solution Architect (Vendor), "
                "Scrum Master (Vendor), Development Team (Vendor). "
                "Add 1 client-side role relevant to HR or IT governance."
            ),
            max_tokens=1800,
        )
        roles = []
        for item in (data if isinstance(data, list) else []):
            try:
                roles.append(RoleResponsibility(**item))
            except Exception:
                pass
        if roles:
            return roles
    except Exception:
        pass
    return [
        RoleResponsibility(
            role="Project Owner",
            responsibilities=["Define and prioritise backlog", "Approve deliverables", "Escalation authority"],
            outcomes=["Signed-off backlog", "Accepted deliverables", "Change log"],
            responsible_party="Client",
        ),
        RoleResponsibility(
            role="Project Manager",
            responsibilities=["Day-to-day coordination", "Risk & issue management", "Status reporting"],
            outcomes=["Weekly status report", "Risk register", "Updated project plan"],
            responsible_party="Vendor",
        ),
        RoleResponsibility(
            role="Solution Architect",
            responsibilities=["Architecture decisions", "Technical leadership", "Integration design"],
            outcomes=["Architecture document", "Integration spec", "ADRs"],
            responsible_party="Vendor",
        ),
        RoleResponsibility(
            role="Development Team",
            responsibilities=["Build and unit-test features", "Code reviews", "Bug fixes"],
            outcomes=["Deployed features", "Test coverage report", "Release notes"],
            responsible_party="Vendor",
        ),
    ]


def _generate_assumptions(arch: ArchitectureDescription, analysis: RequirementsAnalysis) -> List[Assumption]:
    req_titles = "; ".join(f"{r.req_id}: {r.title}" for r in analysis.requirements[:20])
    try:
        data = llm_json(
            system="You are a solution architect writing project assumptions for an RFP response. Return a JSON array only — no prose.",
            user=(
                f"Generate 8-10 project assumptions for this project:\n{_ctx(arch, analysis)}\n"
                f"Key requirements: {req_titles}\n\n"
                "Return a JSON array where each item has:\n"
                '  "category": one of "Platform", "Scope", "Methodology", "Team Schedule", "Exclusions", "Data", "Security"\n'
                '  "text": string (one sentence — the assumption)\n\n'
                "Base the assumptions on the actual requirements listed. "
                "Make them specific to the platform and feature groups, not generic."
            ),
            max_tokens=1200,
        )
        assumptions = []
        for item in (data if isinstance(data, list) else []):
            try:
                assumptions.append(Assumption(**item))
            except Exception:
                pass
        if assumptions:
            return assumptions
    except Exception:
        pass
    return [
        Assumption(category="Platform", text=f"{arch.platform_name} licenses are provisioned before project kick-off."),
        Assumption(category="Scope", text="Scope is limited to requirements defined in the RFP."),
        Assumption(category="Methodology", text="The project follows Agile/Scrum with 2-week sprints."),
    ]


def _generate_credentials(arch: ArchitectureDescription, analysis: RequirementsAnalysis) -> List[Credential]:
    try:
        data = llm_json(
            system="You are writing the credentials section of a consulting proposal. Return a JSON array only — no prose.",
            user=(
                f"Generate 4 past project credentials relevant to this project:\n{_ctx(arch, analysis)}\n\n"
                "Return a JSON array where each item has:\n"
                '  "industry": string (e.g. Financial Services, Retail, Public Sector, Manufacturing)\n'
                '  "project": string (short project title)\n'
                '  "description": string (2 sentences describing the engagement and the vendor\'s role)\n'
                '  "outcomes": array of 3-4 short outcome strings with metrics (e.g. "80% reduction in HR tickets")\n\n'
                "Make the credentials feel authentic, specific, and directly relevant to the platform and feature groups in this project."
            ),
            max_tokens=1800,
        )
        creds = []
        for item in (data if isinstance(data, list) else []):
            try:
                creds.append(Credential(**item))
            except Exception:
                pass
        if creds:
            return creds
    except Exception:
        pass
    return [
        Credential(
            industry="Technology",
            project=f"{arch.platform_name} HR Transformation",
            description="Delivered a comprehensive HR platform transformation for a global enterprise, replacing legacy processes with modern cloud-native solutions.",
            outcomes=["60% reduction in processing time", "Go-live on schedule", "High user adoption rate"],
        ),
    ]


def _generate_plan(
    arch: ArchitectureDescription, analysis: RequirementsAnalysis
) -> Tuple[List[PlanPhase], str]:
    cx = [r.complexity or "" for r in analysis.requirements]
    hi, n = cx.count("High"), len(analysis.requirements)
    try:
        data = llm_json(
            system="You are a project manager writing a delivery plan for a proposal. Return a JSON object only — no prose.",
            user=(
                f"Generate a delivery plan for this project:\n{_ctx(arch, analysis)}\n\n"
                "Return a JSON object with:\n"
                '  "phases": array of objects, each with:\n'
                '    "phase": string (phase name)\n'
                '    "start_month": integer (1-based, sequential)\n'
                '    "duration_months": integer\n'
                '  "note": string (one sentence caveat that the timeline is preliminary)\n\n'
                f"Calibrate the timeline to the actual project scope ({n} requirements, {hi} high-complexity). "
                "Typical range: 8-12 months. "
                "Include: Discovery, Core Build sprint cycles, Integration & UAT, Go-Live, Hypercare."
            ),
            max_tokens=700,
        )
        if isinstance(data, dict):
            phases = []
            for p in data.get("phases", []):
                try:
                    phases.append(PlanPhase(**p))
                except Exception:
                    pass
            note = str(data.get("note", ""))
            if phases:
                return phases, note
    except Exception:
        pass
    return (
        [
            PlanPhase(phase="Discovery & Planning",   start_month=1, duration_months=1),
            PlanPhase(phase="Core Build",              start_month=2, duration_months=4),
            PlanPhase(phase="Integration & UAT",       start_month=6, duration_months=2),
            PlanPhase(phase="Go-Live & Hypercare",     start_month=8, duration_months=2),
        ],
        "This timeline is preliminary and subject to refinement during the Discovery phase.",
    )


def _generate_appendix(arch: ArchitectureDescription, analysis: RequirementsAnalysis) -> List[str]:
    try:
        data = llm_json(
            system="You are writing an appendix for a project proposal. Return a JSON array of strings only — no prose.",
            user=(
                f"Generate 5-7 appendix items for this project:\n{_ctx(arch, analysis)}\n\n"
                "Return a JSON array of short strings (each is an appendix section title or brief label). "
                "Make them specific to the platform, services, and integration patterns in this project. "
                "Examples: 'RICEFW object inventory', 'REST API integration specification', 'Data migration approach'."
            ),
            max_tokens=400,
        )
        if isinstance(data, list) and data:
            return [str(item) for item in data]
    except Exception:
        pass
    return [
        "RICEFW object inventory",
        "Integration specification",
        "Glossary of terms",
        "Technology version matrix",
        "Reference architecture diagram (detailed)",
    ]


# ── Public interface ──────────────────────────────────────────────────────────

def run(arch: ArchitectureDescription, analysis: RequirementsAnalysis) -> DeckContent:
    """Generate all slide content from the RFP context. No hardcoded sections."""
    print("  [Writer] Generating deck content …")

    print("  [Writer] LLM: governance …")
    governance = _generate_governance(arch, analysis)

    print("  [Writer] LLM: delivery & team …")
    delivery_method, team_structure, locations = _generate_delivery(arch, analysis)

    print("  [Writer] LLM: roles & responsibilities …")
    roles = _generate_roles(arch, analysis)

    print("  [Writer] LLM: assumptions …")
    assumptions = _generate_assumptions(arch, analysis)

    print("  [Writer] LLM: credentials …")
    credentials = _generate_credentials(arch, analysis)

    print("  [Writer] LLM: project plan …")
    plan_phases, plan_note = _generate_plan(arch, analysis)

    print("  [Writer] LLM: appendix …")
    appendix_items = _generate_appendix(arch, analysis)

    today = date.today().strftime("%B %Y")

    content = DeckContent(
        client_name     = config.CLIENT_NAME,
        project_name    = config.PROJECT_NAME,
        version         = config.DECK_VERSION,
        authors         = [config.VENDOR_NAME + " Delivery Team"],
        date            = today,
        status          = "DRAFT",
        principles_text = arch.principles_alignment,
        delivery_method = delivery_method,
        team_structure  = team_structure,
        locations       = locations,
        governance      = governance,
        roles           = roles,
        plan_phases     = plan_phases,
        plan_note       = plan_note,
        assumptions     = assumptions,
        credentials     = credentials,
        appendix_items  = appendix_items,
    )

    print(
        f"  [Writer] → DeckContent generated ✓  "
        f"({len(roles)} roles · {len(assumptions)} assumptions · "
        f"{len(credentials)} credentials · {len(plan_phases)} plan phases)"
    )
    return content
